config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find, only: [:show, :destroy, :edit, :update]

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(params_flats)
    @flat.save

    redirect_to flat_path(@flat)
  end

  def show
  end

  def edit
  end

  def update
    @flat.update(params_flats)
    @flat.save

    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy

    redirect_to flats_path
  end

  private

  def find
    @flat = Flat.find(params[:id])
  end

  def params_flats
    params.require(:flat).permit(:description, :name, :address, :number_of_guests, :price_per_night, :picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container">
  <h1 class='mt-3 text-center'>Edit a flat</h1>
  <%= simple_form_for(@flat) do |f|%>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :picture %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <div class="text-center">
  <%= link_to 'Back', flats_path, class: 'btn btn-info mt-2'  %>
  <%= f.submit 'Edit it!', class: 'btn btn-success mt-2' %>
  </div>
  <% end %>
</div>

app/views/flats/index.html.erb
<div class="container">
  <h1>All our flats</h1>
  <p>All <%= "#{@flats.count}" %> flats. </p>
  <div class="card-container">
  <% @flats.each do |flat| %>
    <div class="card-product mb-2">
      <img src= <%= flat.picture %>>
      <div class="card-product-infos">
          <h2> <%= link_to flat.name, flat_path(flat)  %> </h2>
          <p> <%= flat.address %> </p>
          <p> <i class="fas fa-dollar-sign"></i> <%= flat.price_per_night %> </p>
          <p><i class="fas fa-user-friends"></i> <%= flat.number_of_guests %> </p>
      </div>
      <div class="card-product-actions">
        <a data-method='delete' href=<%="#{flat_path(flat)}"  %> ><i class="fas fa-trash"></i></a>
        <a href=<%="#{edit_flat_path(flat)}"  %> ><i class="fas fa-edit"></i></a>
      </div>
    </div>
  <% end %>
  </div>


</div>

app/views/flats/new.html.erb
<div class="container">
  <h1 class='mt-3 text-center'>Add a flat</h1>
  <%= simple_form_for(@flat) do |f|%>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :picture %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <div class="text-center">
  <%= link_to 'Back', flats_path, class: 'btn btn-info mt-2'  %>
  <%= f.submit 'Add it!', class: 'btn btn-success mt-2' %>
  </div>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="container text-center">
  <h1 class="mt-5">
    <%= @flat.name %>
  </h1>

  <div class="card-category p-2" style="background-color: rgba(200,200,200,0.5); width: 400px; margin: 10px auto;">
    <p> <%= @flat.description %> </p>
    <p> <i class="fas fa-dollar-sign"></i> <%= @flat.price_per_night %> </p>
    <p><i class="fas fa-user-friends"></i> <%= @flat.number_of_guests %> </p>
  </div>
  <div class="text-center">
   <%= link_to 'Back', flats_path, class: 'btn btn-info mt-2'  %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar">
      <p>
      <%= link_to 'Simple AirBnB', flats_path %>
      </p>
      <%= link_to "Add Flat", new_flat_path, class: 'btn btn-primary'  %>
    </div>
    <%= yield %>
  </body>
</html>